title: Discrete Digital Clock Manual
description: Documentation and showcase of the Discrete Digital Clock
theme: minima
author: Bla≈æ Jerman

minima:
  social_links:
    github: blazjerman

header_pages:
  - detailed.md
  - buy.md
  